import { Companydesignation } from "./Companydesignation";
import { Companyindustry } from "./Companyindustry";
import { Companytechnology } from "./Companytechnology";
import { Jobposting } from "./Jobposting";
import { Login } from "./Login";
import { Paatashalaregistration } from "./Paatasalagistration";

export type Companydatum = {
  Id: number;
  Url: string;
  Name: string;
  Email: string;
  Password: string;
  Address: string;
  PhoneNumber: string;
  Gstnumber: string;
  ContactPerson: string;
  AddressLine1: string;
  City: string;
  State: string;
  ZipCode: string;
  Country: string;
  ParentCompanyId: number;
  IsDeleted: number;
  IsActive: number;
  DateOfRegistration: Date | null;
  CompanySize: number;
  LogoPath: string;
  About: string;
  HeadQuarters: string;
  VideoPath: string;
  PresentationPath: string;
  DocumentPath: string;
  AudioPath: string;
  UserRoleId: number;
  Companydesignations: Companydesignation[];
  Companytechnologies: Companytechnology[];
  Companyindustires: Companyindustry[];
  Jobpostings: Jobposting[];
  Logins: Login[];
  Paatashalaregistrations: Paatashalaregistration[];
};

export type PostCompanydatum = {
  Id: number;
  Url: string;
  Name: string;
  Email: string;
  Password: string;
  Address: string;
  PhoneNumber: string;
  Gstnumber: string;
  ContactPerson: string;
  AddressLine1: string;
  City: string;
  State: string;
  ZipCode: string;
  Country: string;
  ParentCompanyId: number;
  IsDeleted: number;
  IsActive: number;
  DateOfRegistration: Date | null;
  CompanySize: number;
  LogoPath: string;
  About: string;
  HeadQuarters: string;
  VideoPath: string;
  PresentationPath: string;
  DocumentPath: string;
  AudioPath: string;
  UserRoleId: number;
};
