import { Collegejobposting } from "./Collegejobposting";
import { Collegejobpostingschedule } from "./Collegejobpostingschedule";
import { Companydatum } from "./Companydatum";
import { Jobinterviewround } from "./Jobinterviewround";
import { JobpostingsEligiblestudent } from "./JobpostingsEligibleStudent";
import { JobpostingSelectedstudent } from "./JobpostingSelectedstudent";
import { Technology } from "./Technology";
import { JobpostingSkill } from "./JobpostingSkill";
import { CompanyJobBatch } from "./CompanyJobBatch";
import { CompanyJobCourse } from "./CompanyJobCourse";
import { Jobinterviewpanel } from "./Jobinterviewpanel";

export type Jobposting = {
  Id: number;
  CompanyId?: number;
  JobRole?: string;
  JobDescription?: string;
  ValidFrom?: Date | null;
  ValidTill?: Date | null;
  Positions?: number;
  QuantityFilled?: number;
  IsClosed?: number;
  IsDeleted?: number;
  TechnologyId?: number;
  Salary?: number;
  Location?: string;
  Experience?: string;
  JobType?: string;
  Shift?: string;
  ModeOfWork?: string;
  DriveDate?: Date | null;
  Vacancies?: number;
  MinSslcpercentage?: number;
  MinPucpercentage?: number;
  MinCgpa?: number;
  BacklogsAllowed?: number;
  Collegejobpostings: Collegejobposting[];
  Collegejobpostingschedules: Collegejobpostingschedule[];
  Company: Companydatum;
  Jobinterviewrounds: Jobinterviewround[];
  JobpostingSelectedstudents: JobpostingSelectedstudent[];
  JobpostingsEligiblestudents: JobpostingsEligiblestudent[];
  Technology: Technology;
  Technologies: Technology[];
  JobpostingSkills?: JobpostingSkill[];
  CompanyJobBatches?: CompanyJobBatch[];
  CompanyJobCourses?: CompanyJobCourse[];
  Jobinterviewpanels: Jobinterviewpanel[];
};

export type PostJobposting = {
  Id: number;
  CompanyId?: number;
  JobRole?: string;
  JobDescription?: string;
  ValidFrom?: Date | null;
  ValidTill?: Date | null;
  Positions?: number;
  QuantityFilled?: number;
  IsClosed?: number;
  IsDeleted?: number;

  Salary?: number;
  Location?: string;
  Experience?: string;
  JobType?: string;
  Shift?: string;
  ModeOfWork?: string;
  DriveDate?: Date | null;
  Vacancies?: number;
  MinSslcpercentage?: number;
  MinPucpercentage?: number;
  MinCgpa?: number;
  BacklogsAllowed?: number;
  Collegejobpostings: { JobPostingId?: number; CollegeId?: number }[];
  // Technologies: Technology[];
  JobpostingSkills?: { SkillId?: number; JobPostingId?: number }[];
  CompanyJobBatches?: { JobPostingId?: number; BatchId?: number }[];
  CompanyJobCourses?: { JobPostingId?: number; CourseId?: number }[];
};
