import { Batch } from "./Batch";
import { Campusregistration } from "./Campusregistration";
import { JobpostingSelectedstudent } from "./JobpostingSelectedstudent";
import { JobpostingsEligiblestudent } from "./JobpostingsEligibleStudent";
import { JobpostStudentround } from "./JobpostStudentround";
import { Login } from "./Login";
import { Skill } from "./Skill";
import { Studentacademic } from "./Studentacademic";
import { Studentplaced } from "./Studentplaced";
import { StudentSkill } from "./StudentSkill";

export type PatchTblStudent = Tblstudent | {};

export type Tblstudent = {
  Id: number;
  OrgId: number;
  FirstName: string;
  MiddleName: string;
  LastName: string;
  BatchId: number;
  AadharCardNumber: string;
  PermanentAddress: string;
  CurrentAddress: string;
  Email: string;
  PhoneNumber: string;
  FatherName: string;
  FatherPhoneNumber: string;
  DateOfBirth: Date | null;
  RollNo: string;
  MotherName: string;
  MotherPhoneNumber: string;
  Gender: string;
  IsSentInvitation: boolean;
  Batch: Batch;
  Pannumber: string;
  BloodGroup: string;
  JobpostStudentrounds: JobpostStudentround[];
  JobpostingSelectedstudents: JobpostingSelectedstudent[];
  JobpostingsEligiblestudents: JobpostingsEligiblestudent[];
  Logins: Login[];
  Org: Campusregistration;
  Studentacademics: Studentacademic[];
  StudentSkills: StudentSkill[];
  Studentplaceds: Studentplaced[];
  skills: string;
};

export type PostTblstudent = {
  Id: number;
  FirstName: string;
  MiddleName: string;
  LastName: string;
  BatchId: number;
  AadharCardNumber: string;
  PermanentAddress: string;
  CurrentAddress: string;
  Email: string;
  PhoneNumber: string;
  FatherName: string;
  FatherPhoneNumber: string;
  MotherName: string;
  MotherPhoneNumber: string;
  DateOfBirth: Date | null;
  RollNo: string;
  Pannumber: string;
  BloodGroup: string;
  Batch: { Id: number; Name: string };
  Studentacademics: {
    StudentId: number;
    CourseId: number;
    StreamId: number;
    Cgpa: number;
    TenthMarks: number;
    TwelthMarks: number;
    TenthBoard: string;
    TwelthBoard: string;
    TenthPassedOutYear: number;
    TwelthPassedOutYear: number;
    TenthSchoolName: string;
    TwelthSchoolName: string;
    DiplomaCollegeName: string;
    StudentSemesterMarks: {
      StudentAcademicId?: number;
      Semester?: number;
      Sgpa?: number;
    }[];
  };
  StudentSkills: { SkillId?: number; StudentId?: number }[];
  skills: string;
};
