import { Batch } from "./Batch";
import { Campusregistration } from "./Campusregistration";
import { JobpostingSelectedstudent } from "./JobpostingSelectedstudent";
import { JobpostingsEligiblestudent } from "./JobpostingsEligibleStudent";
import { JobpostStudentround } from "./JobpostStudentround";
import { Login } from "./Login";
import { Skill } from "./Skill";
import { Studentacademic } from "./Studentacademic";
import { Studentplaced } from "./Studentplaced";
import { StudentSkill } from "./StudentSkill";

export type PatchTblStudent = Tblstudent | {};

export type Tblstudent = {
  Id: number;
  OrgId: number;
  FirstName: string;
  LastName: string;
  BatchId: number;
  AadharCardNumber: string;
  PermanentAddress: string;
  CurrentAddress: string;
  Email: string;
  PhoneNumber: string;
  FatherName: string;
  FatherPhoneNumber: string;
  DateOfBirth: Date;
  RollNo: string;
  BloodGroup: string;
  MiddleName: string;
  Pannumber: string;
  MotherName: string;
  MotherPhoneNumber: string;
  Gender: string;
  Batch: Batch;
  JobpostStudentrounds: JobpostStudentround[];
  JobpostingSelectedstudents: JobpostingSelectedstudent[];
  JobpostingsEligiblestudents: JobpostingsEligiblestudent[];
  Logins: Login[];
  Org: Campusregistration;
  Studentacademics: Studentacademic[];
  StudentSkills: StudentSkill[];
  Studentplaceds: Studentplaced[];
  skills: string;
};

export type PostTblstudent = {
  Id: number;
  FirstName: string;
  LastName: string;
  BatchId: number;
  AadharCardNumber: string;
  PermanentAddress: string;
  CurrentAddress: string;
  Email: string;
  PhoneNumber: string;
  FatherName: string;
  FatherPhoneNumber: string;
  DateOfBirth: Date;
  RollNo: string;
  BloodGroup: string;
  MiddleName: string;
  Pannumber: string;
  MotherName: string;
  MotherPhoneNumber: string;
  Gender: string;
  Batch: Batch;
  Studentacademics: Studentacademic[];
  StudentSkills: StudentSkill[];
};
