export type CompanyRegistration = {
  Id: number;
  Url: string;
  Name: string;
  Address: string;
  PhoneNumber: string;
  Gstnumber: string;
  ContactPerson: string;
  AddressLine1: string;
  City: string;
  State: string;
  ZipCode: string;
  Country: string;
  ParentCompanyId: string;
  IsDeleted: boolean;
  Password: string;
  UserRoleId: number;
  Email: string;
  DateOfRegistration: Date;
  IsActive: boolean;
};
